name: "TEST"

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 500
      - name: "Setup Node"
        uses: actions/setup-node@main
        with:
          node-version: "16"
          cache: npm
      - name: "Run Tests"
        run: |
          npm ci && npm run test:coverage
      - name: "Read Semver Info"
        id: "semver_info"
        uses: YunaBraska/semver-info-action@main
        with:
          semver-a: 'v1.2.3-rc.4'
          semver-b: 'v5.6.7-rc.8'
          fallBack-semver-a: '0.0.1'
          fallBack-semver-b: '0.0.1'
      - name: "Print Semver Info"
        run: |
          echo "clean_semver         [${{ steps.semver_info.outputs.clean_semver }}]"
          echo "is_stable            [${{ steps.semver_info.outputs.is_stable }}]"
          echo "is_valid_semver      [${{ steps.semver_info.outputs.is_valid_semver }}]"
          echo "is_major_change      [${{ steps.semver_info.outputs.is_major_change }}]"
          echo "is_a_greater_than_b  [${{ steps.semver_info.outputs.is_greater_a }}]"
          echo "next_major           [${{ steps.semver_info.outputs.next_major }}]"
          echo "next_major_a         [${{ steps.semver_info.outputs.next_major_a }}]"
          echo "next_major_b         [${{ steps.semver_info.outputs.next_major_b }}]"
          echo "next_minor           [${{ steps.semver_info.outputs.next_minor }}]"
          echo "next_patch           [${{ steps.semver_info.outputs.next_patch }}]"
          echo "next_rc              [${{ steps.semver_info.outputs.next_rc }}]"
          echo "version_txt          [${{ steps.semver_info.outputs.version_txt }}]"
          echo "version_txt_path     [${{ steps.semver_info.outputs.version_txt_path }}]"
