name: "TEST"

on:
  push:
    # Already covered by "publish.yml" workflow
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'
      - '!main'
      - '!default'
    tags-ignore:
      - '**'
  workflow_dispatch:
    ref:
      type: string
      description: "[ref] e.g. branch, tag or commit to checkout [default: github.ref_name || github.head_ref ]"
      required: false

jobs:
  node_test:
    name: "Node Test"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_node_test.yml@main
    with:
      ref: ${{ inputs.ref || github.ref_name || github.head_ref }}
  show_case:
    needs: node_test
    name: "Show Case"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
      - name: "Read Semver Info"
        id: "semver_info"
        uses: YunaBraska/semver-info-action@main
        with:
          semver-a: 'v1.2.3-rc.4'
          semver-b: 'v5.6.7-rc.8'
          fallBack-semver-a: '0.0.1'
          fallBack-semver-b: '0.0.1'
      - name: "Print Semver Info"
        run: |
          echo "clean_semver         [${{ steps.semver_info.outputs.clean_semver }}]"
          echo "is_stable            [${{ steps.semver_info.outputs.is_stable }}]"
          echo "is_valid_semver      [${{ steps.semver_info.outputs.is_valid_semver }}]"
          echo "is_major_change      [${{ steps.semver_info.outputs.is_major_change }}]"
          echo "is_a_greater_than_b  [${{ steps.semver_info.outputs.is_greater_a }}]"
          echo "next_major           [${{ steps.semver_info.outputs.next_major }}]"
          echo "next_major_a         [${{ steps.semver_info.outputs.next_major_a }}]"
          echo "next_major_b         [${{ steps.semver_info.outputs.next_major_b }}]"
          echo "next_minor           [${{ steps.semver_info.outputs.next_minor }}]"
          echo "next_patch           [${{ steps.semver_info.outputs.next_patch }}]"
          echo "next_rc              [${{ steps.semver_info.outputs.next_rc }}]"
          echo "version_txt          [${{ steps.semver_info.outputs.version_txt }}]"
          echo "version_txt_path     [${{ steps.semver_info.outputs.version_txt_path }}]"
